### PR TITLE
No longer needs astropy 4.0rc

### PR DESCRIPTION
**Pull request by pllim**
I think... Tagging Adrian just to make sure the CI failures are expected.

### CODE REVIEW

**Comment by pllim** [comment]
@adrn , I thought you added CI. How come it didn't kick off?

**Comment by adrn** [comment]
Errr that's weird...looking into it now!

**Comment by adrn** [comment]
Everything looks fine from what I can see with my permissions. Someone with true admin rights in this repo should check to see when the last webhook was delivered to circleci!

**Comment by adrn** [comment]
It looks like CI might only be running for me...

I think we'll need someone from the CoCo to fix this on CircleCI, because I can't access the project settings!

**Comment by eteq** [comment]
@adrn - the webhook looked fine to me... But I also gave you admin powers so maybe you'll see something I didn't?  (I can also try fiddling in the CircleCI config if need be, although I think you should have that too now.)

**Comment by adrn** [comment]
Thanks! Huh, yea, the webhook looks right to me too...I'm stumped!

**Comment by bsipocz** [comment]
are you watching the repo on circle? it doesn't (didn't) pick up builds unless being watched/followed

**Comment by adrn** [comment]
@pllim has to watch it, or astropy has to watch it?

**Comment by adrn** [comment]
Ah! I just turned this on, maybe that will do it: 
image

**Comment by adrn** [comment]
Woot!

**Comment by bsipocz** [comment]
> @pllim has to watch it, or astropy has to watch it?

not @pllim, but someone from the org? or maybe just someone, anyone.

**Comment by stargaser** [comment]
I started following this repo as @stargaser but maybe that's not what is needed?

**Comment by bsipocz** [comment]
No, it's watching the circleCI, but as it turned out that wasn't the issue. Now it all seems good that Adrian change the settings.

**Comment by pllim** [comment]
Same failures as #112 , which is out of scope. So I am merging this. Thanks, everyone!

**Pull request merged**
