### PR TITLE
update environment activation instructions

### PR DESCRIPTION
**Pull request by r-lange**
I followed the environment installation and activation instruction on my Mac, however, to activate an environment is a different command to Windows (which is the example given in the instructions). Note I used the full version of conda as I had it already installed.

### CODE REVIEW

**Comment by r-lange** [comment]
I have double checked my conda version, after updating it the conda activate command works, so the instructions should include info on the required conda version and/or updated install instructions as given by the pull request.

**Comment by r-lange** [comment]
Yes, I realised that `conda activate` works with an updated version of conda after I submitted the pull request. 
Best would be to add a line to update conda if they already have an older version installed.

**Comment by stargaser** [comment]
ok, got it @r-lange! Would you like to update this PR to note the conda version, if you have time to do it?

**Comment by r-lange** [comment]
I am about to hop onto my first flight. I should have some time when on my stop-over later today.

**Comment by r-lange** [comment]
@stargaser I've updated the PR.

**Pull request merged**
