### PR TITLE
Update Photutils notebooks

### LINKED ISSUE #85: Error in photutils_overview
In the cell `In[27]`, running:
```python
phot = aperture_photometry(data * unit, aperture, error=tot_error * u.adu)
phot
```

I get this traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-dd856df23ce6> in <module>
----> 1 phot = aperture_photometry(data * unit, aperture, error=tot_error * u.adu)
      2 phot

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    519                             kwargs[new_name[i]] = value
    520 
--> 521             return function(*args, **kwargs)
    522 
    523         return wrapper

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/photutils/aperture/photometry.py in aperture_photometry(data, apertures, error, mask, method, subpixels, unit, wcs)
    196     # handle data, error, and unit inputs
    197     # output data and error are ndarray without units
--> 198     data, error, unit = _handle_units(data, error, unit)
    199 
    200     # compute variance and apply input mask

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/photutils/aperture/_photometry_utils.py in _handle_units(data, error, unit)
    136         if error is not None:
    137             if unit != error.unit:
--> 138                 raise ValueError('data and error must have the same units.')
    139             error = error.value
    140 

ValueError: data and error must have the same units.
```

### LINKED ISSUE #86: Error in photutils_local_background
In the cell `In[12]`, running this code:
```python
phot['annulus_mean'] = phot['annulus_sum'] / bkg_aper.area()
phot
```

I get this traceback:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-49433b94b10c> in <module>
----> 1 phot['annulus_mean'] = phot['annulus_sum'] / bkg_aper.area()
      2 phot

TypeError: 'float' object is not callable
```
I guess `.area` is now an attribute?

### LINKED ISSUE #87: Error in photutils_extended
In the cell `In[31]`, running this code:
```python
from photutils.utils import random_cmap

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 8))
ax1.imshow(data, norm=norm)
lbl1 = ax1.set_title('Data')
ax2.imshow(segm, cmap=segm.cmap())
lbl2 = ax2.set_title('Segmentation Image')
```

I get this traceback:
```
ImportError                               Traceback (most recent call last)
<ipython-input-31-63b082d1cf72> in <module>
----> 1 from photutils.utils import random_cmap
      2 
      3 fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 8))
      4 ax1.imshow(data, norm=norm)
      5 lbl1 = ax1.set_title('Data')

ImportError: cannot import name 'random_cmap' from 'photutils.utils' (/Users/apricewhelan/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/photutils/utils/__init__.py)
```

### PR DESCRIPTION
**Pull request by larrybradley**
Improvements and updates for the latest version of Photutils.

I still need to make some updates to `image_psf_photometry_withNIRCam.ipynb` to programmatically download the data, but I'll do that in a separate PR.

EDIT:
Fixes #85
Fixes #86
Fixes #87

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, Larry! Does this address #9 or #13 too?

@shannnnnyyy , since you would be the instructor teaching this section, please review.

Thanks, everyone!

**Comment by larrybradley** [comment]
@pllim I didn't address those issues.  I don't think there are Photutils slides (I never wrote any).

**Comment by larrybradley** [comment]
I'm puzzled about #13 because there aren't any exercises in the Photutils notebook.  Perhaps *an* exercise more fun than not?  🤔

**Comment by pllim** [comment]
@bmorris3 , do you have any insight about how much fun an exercise of `photutils` would be with your recent workshop experience?

**Comment by eteq** [comment]
@larrybradley - yes, I'd interpret #13 as "there should be an exercise" - I'm guessing that was just grouping together broad feedback.  

That could be a follow-on PR, perhaps to be done by @shannnnnyyy if she has time, though?

**Comment by larrybradley** [comment]
Fixes #85
Fixes #86 
Fixes #87

**Comment by pllim** [comment]
You know what... I'll just YOLO this one and merge it now. @shannnnnyyy , if you have any proposed changes, please open a follow-up PR. Thanks!

**Comment by shannnnnyyy** [comment]
@pllim go ahead - I'm working through the notebooks now and looking for a place to add an exercise. I'll open up a new PR once I've done that.

**Comment by pllim** [comment]
Thank you for your understanding!

**Pull request merged**
