### PR TITLE
Update schedule with AAS 2020 workshop instructors

### PR DESCRIPTION
**Pull request by eteq**
This PR updates the instructor names for the 2020 AAS Workshop.  Below are the folks assigned sections.  Please check off your name here to confirm you've looked at this and are ok with it.

- [x] @eteq
- [x] @adrn
- [x] @pllim 
- [x] @bsipocz 
- [x] @stargaser 
- [x] @shannnnnyyy 
- [x] @r-lange

### CODE REVIEW

**Comment by bsipocz** [comment]
can't edit, but I'm ok with the schedule

**Comment by bsipocz** [comment]
Btw, tables: what about show casing TimeSeries in the advanced tables notebook?

**Comment by eteq** [comment]
I like that idea @bsipocz - do you want me to change the title to mention that specifically?

**Comment by r-lange** [comment]
I can't edit either, but am happy with the schedule

**Comment by pllim** [comment]
@eteq , all the mentioned parties have agreed to this. Shall we merge?

**Comment by bsipocz** [comment]
> I like that idea @bsipocz - do you want me to change the title to mention that specifically?

let's change it once the notebook is updated.

**Comment by bsipocz** [comment]
issue is opened for the update: #77, so this can be merged now as is

**Pull request merged**
