### PR TITLE
Update coordinates notebook

### LINKED ISSUE #84: Demonstrate proper motions / velocities in astropy.coordinates
The current coordinates tutorial does not contain any mention of velocities or proper motions. It probably should! I'd be happy to add some content to demonstrate this -- is that ok with everyone?

### PR DESCRIPTION
**Pull request by adrn**
~~I got a bit carried away and rewrote the coordinates tutorial! I kept most of the concepts, but swapped out the HCG stuff with some Gaia examples to build up to using proper motion and velocity data. The last section uses FITS and WCS to display an image, but I don't think we'll get there in the time I have, so that can just be an exercise for the attendees for their own time.~~

~~I haven't yet updated the solutions notebook (the astropy_coordinates.ipynb currently contains the solutions in case anyone has the strength to review this!).~~

This PR now just updates the solutions notebook.

This fixes #84

### CODE REVIEW

**Comment by pllim** [comment]
`+2,528 −1,005` 😱

**Comment by adrn** [comment]
> `+2,528 −1,005` 😱

A lot of that comes from the FITS files I added!

**Comment by pllim** [comment]
Can we close this *without* merge with #111 merged?

**Comment by adrn** [comment]
I'm going to rebase and update the solutions notebook, so this will be necessary...soon

**Comment by adrn** [comment]
Build failure is because of #112 and unrelated to this PR.

**Pull request merged**
