### PR TITLE
Update ccdproc notebooks 

### PR DESCRIPTION
**Pull request by mwcraig**
This PR 

+ fixes some typos,
+ adds a bit more explanation
+ adds a before and after plot to the image combination notebook

### CODE REVIEW

**Comment by mwcraig** [comment]
@stargaser -- this is ready for review, and runs successfully locally.

**Review by stargaser — APPROVED** [review]
Thanks for the update. The changes look good to me.

I anticipate some questions about ccdproc v2.2. I tried an update from github using pip and got version 2.1.2.dev24+g91f2c46. I still see a number of warnings. My experience has been that workshop participants become alarmed about seeing those. In other groups we have been filtering warnings so that these don't show up. Is that an approach that would be okay or do you think it is just better to explain that the warnings are not important?

I'm approving these changes but will wait a day before merging in case we want to address some of those points.

**Comment by mwcraig** [comment]
Hi,

I'm hoping to do the 2.2 release later tonight or tomorrow (Monday) morning.

**Comment by stargaser** [comment]
Very good, I will re-test after 2.2 is released!

**Comment by mwcraig** [comment]
Just upploaded 2.2 to pypi...

**Comment by mwcraig** [comment]
...and just merged the conda-forge recipe, so it should be available in conda in ~1 hour

**Comment by stargaser** [comment]
conda now installs ccdproc v2.2 and it works with these notebooks. 

The warnings are still there. For the NAVO workshops we suppress these. I find myself wanting to do that here, but want to ask first. An alternative is to verbally reassure people that the warnings are not important.

In the first notebook, I added to the import code block:
```
# Suppress unimportant warnings
import warnings
warnings.filterwarnings("ignore", '.*RADECSYS=.*')
warnings.filterwarnings("ignore", '.*block_reduce was moved*', append=True)
warnings.filterwarnings("ignore", '.*meta, unit, wcs*', module='astropy.nddata.decorators')
```

and in the second notebook's import block:
```
# Suppress unimportant warnings
import warnings
warnings.filterwarnings("ignore", '.*block_reduce was moved*', append=True)
warnings.filterwarnings("ignore", '.*uncertainty, mask, meta, unit*', module='astropy.nddata.decorators')
```

**Comment by stargaser** [comment]
I'm going to merge this one...will think about filtering warnings.

**Pull request merged**
