### PR TITLE
Update to Python 3.6/Astropy 3.1 as well as hyperlink fixes and bug/typo corrections.

### LINKED ISSUE #11: keep environment file updated
remove ginga and other unused packages. 
change to astropy channel.

add instructions somewhere if you add new tutorials to update the yaml file.
Hopefully testing will help with this.

### LINKED ISSUE #28: psf phot notebook needs numpy imported and photutils updates
This notebook is missing an import of numpy: https://github.com/astropy/astropy-workshop/blob/master/09-Photutils/gaussian_psf_photometry.ipynb

also, I think `mmm_bkg.sigma_clip.iters` changed to `mmm_bkg.sigma_clip.maxiters`

### PR DESCRIPTION
**Pull request by JuanCab**
Revisions/Bug fixes to the workshop files to get them ready for Python 3.6/Astropy 3.1 and the AAS workshop in Jan. 2019.

- Updated the environment.yml files to use Python 3.6 (and thus also astropy 3.1 hopefully).  Also switched from astroconda to astropy and conda-forge for source channels for macos/linux. Dropped installation of ds9 (which is no longer used) and updated matplotlib, numpy, and astropy required versions to much more recent versions. These changes allowed a unified environment.yml file for macos/windows/linux and removed the need for windows specific instructions in the README.md.  So the redundant files were removed and the installation instructions cleaned up. (I believe this resolves #11)

- All hyperlinks to documentation checked and replaced any links to "latest" version of documentation to "stable" version (in many cases, the "latest" version links were broken).  This was done to several notebooks.

- And in the PhotUtils/gaussian_psf_photometry notebook
     - Replaced use of imported OrderedDict with built-in dict object
     - Fixed a bad request for deprecated `iters` value from a sigma_clip object. It appears the proper name of the value is `maxiters`.  This fixed the notebook so it can run in astropy 3.1.  (Resolves #28)
     - Added a numpy import which was forgotten.  (Resolves #28)
     - One typo fixed (spelling of "unknown")

### CODE REVIEW

**Comment by sosey** [comment]
awesome. I jumped the gun a bit last night, will you cross reference here, using "closes #issuenumber" syntax any of the issues that this PR solves? 

Also, I think we should update the environment.yaml to point to these more recent versions:
astropy >= 3
numpy >=1.12,  # 1.7 is really old at this point. 
ds9 can be removed since it's not being used in this version of the workshop
matplotlib >= 2.2.3 #the LTS version

**Comment by JuanCab** [comment]
If we drop ds9 I think we could drop astroconda as the source channel if I understand the sourcing of the packages and use Conda-forge and astropy.  I could test this.  I think updating numpy makes sense as well.  Should I go ahead and do this?

**Comment by sosey** [comment]
yah, I think switching the channels is reasonable, it gives us a source that should have good builds of everything for win/osx/linux

**Comment by JuanCab** [comment]
> yah, I think switching the channels is reasonable, it gives us a source that should have good builds of everything for win/osx/linux

We could switch the instructions to use environment.yml for all of them, now that windows wouldn't need to be any different, I think.  I'll test that as well and if so, I will make the changes to the installation instructions and add them to this PR.

**Pull request merged**
