### PR TITLE
Mention lightkurve in OOP intro

### PR DESCRIPTION
**Pull request by bmorris3**
When I teach the OOP tutorial, I always mention that the `LightCurve` object created in the notebook is only meant for pedagogical purposes. I suggest that if you want to do real research with light curves, you would benefit greatly from using the `lightkurve` package.

In this PR, I put that commentary into text in the notebook.

### CODE REVIEW

**Comment by bmorris3** [comment]
(Also, happy second birthday to this notebook, introduced in https://github.com/astropy/astropy-workshop/pull/163 🎉 🍰)

**Comment by bmorris3** [comment]
Hi @nstarman – is it possible astropy/astropy#12136 broke the tests in these notebooks?

**Comment by nstarman** [comment]
The following should work.

```python
from astropy.cosmology import parameters

parameters.available
```

While not deprecated, the ``parameters`` module is mostly legacy. For a one-liner use

```python
astropy.cosmology.realizations.available
```

**Comment by bmorris3** [comment]
Thanks @nstarman, all fixed!

**Pull request merged**
