### PR TITLE
Fix typo and set default values so specutils_analysis executes

### LINKED ISSUE #89: Error in Specutils_analysis
Cell: `In[8]`

```python
from specutils.manipulation import extract_region

subspec = extract_region(sdss_spec, pixel_region)
plt.step(subspec.wavelength, subspec.flux)

analysis.snr(subspec)
```

I get this traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/nddata/mixins/ndslicing.py in _slice_wcs(self, item)
    122         try:
--> 123             llwcs = SlicedLowLevelWCS(self.wcs.low_level_wcs, item)
    124             return HighLevelWCSWrapper(llwcs)

AttributeError: 'GWCSAdapter' object has no attribute 'low_level_wcs'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-8-1cc89492a8c0> in <module>
      1 from specutils.manipulation import extract_region
      2 
----> 3 subspec = extract_region(sdss_spec, pixel_region)
      4 plt.step(subspec.wavelength, subspec.flux)
      5 

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/specutils/manipulation/extract_spectral_region.py in extract_region(spectrum, region)
    133                 left_index, right_index = right_index, left_index
    134 
--> 135             extracted_spectrum.append(spectrum[left_index:right_index])
    136 
    137     # If there is only one subregion in the region then we will

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/specutils/spectra/spectrum1d.py in __getitem__(self, item)
    170                     if self.uncertainty is not None else None)
    171 
--> 172         return super().__getitem__(item)
    173 
    174     def _copy(self, **kwargs):

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/nddata/mixins/ndslicing.py in __getitem__(self, item)
     60 
     61         # Let the other methods handle slicing.
---> 62         kwargs = self._slice(item)
     63         return self.__class__(**kwargs)
     64 

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/nddata/mixins/ndslicing.py in _slice(self, item)
     90         kwargs['uncertainty'] = self._slice_uncertainty(item)
     91         kwargs['mask'] = self._slice_mask(item)
---> 92         kwargs['wcs'] = self._slice_wcs(item)
     93         # Attributes which are copied and not intended to be sliced
     94         kwargs['unit'] = self.unit

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/nddata/mixins/ndslicing.py in _slice_wcs(self, item)
    124             return HighLevelWCSWrapper(llwcs)
    125         except Exception as err:
--> 126             self._handle_wcs_slicing_error(err, item)
    127 
    128     # Implement this in a method to allow subclasses to customise the error.

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astropy/nddata/mixins/ndslicing.py in _handle_wcs_slicing_error(self, err, item)
    130         raise ValueError(f"Slicing the WCS object with the slice '{item}' "
    131         "failed, if you want to slice the NDData object without the WCS, you "
--> 132         "can remove by setting `NDData.wcs = None` and then retry.") from err

ValueError: Slicing the WCS object with the slice 'slice(2100, 2600, None)' failed, if you want to slice the NDData object without the WCS, you can remove by setting `NDData.wcs = None` and then retry.
```

### PR DESCRIPTION
**Pull request by adrn**
This hopefully fixes #89

### CODE REVIEW

**Comment by pllim** [comment]
Hmm @eteq moved #89 to "done" status on the board but the issue is still open.

**Comment by adrn** [comment]
Yea, he sent me a message somewhere. Basically: spectutils 0.7 fixed the incompatibility error, but there is a point in the notebook where users have to enter a lower and upper value in order for the notebook to execute, which means it will still fail in the CI build. This adds default values for those bounds

**Comment by adrn** [comment]
All notebooks execute successfully with this!

**Comment by pllim** [comment]
Let's do this! Windows failure can be handled in a separate PR.

**Pull request merged**
